### ISSUE TITLE
WoT Tutorial from TUM for Documentations Page

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-marketing#112]
From today's marketing call:
- we need some kind of ok from the TUM side to share this material
- in the material there are many logistic information for the students--> we should remove this
- the videos should be also modified that non-based student information is available
- it would be good if there is no PDF. can that material transformed to html pages?

**Comment by danielpeintner** [comment]
>     * it would be good if there is no PDF. can that material transformed to html pages?

Yet another possibility could be to use a online pdf reader like https://mozilla.github.io/pdf.js/ and embed it on our site (no need to launch a local PDF application)

**Comment by egekorkan** [comment]
yeah or simply use your browser's pdf reader that is available in all the browsers

**Comment by danielpeintner** [comment]
> yeah or simply use your browser's pdf reader that is available in all the browsers

The problem I see here is that it opens a new window/tab and the user is gone. I prefer having something embedded in *our* site so that it still gives the feeling being on the WoT website.

**Comment by egekorkan** [comment]
Are there any list of requirements for how the tutorials should be structured? I will be doing the same course next semester, starts on the 15.04.2021. I can restructure the content so that I can hit two birds (lecture and tutorial) with one stone (same basic slide deck). My information flow for the lab is as follows:
1. Introducing the lab 
2. Introducing payload formats and JSON Schema
3. Introducing WoT and Thing Description
4. Introducing Protocols
5. Introducing Scripting API and node-wot

**Comment by egekorkan** [comment]
Given they had to be removed, closing.
