### ISSUE TITLE
We should link to the existing explainer about WoT

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-marketing#126]
There is an explainer [existing](https://github.com/w3c/wot-thing-description/blob/master/explainer/Explainer.md) which we should update and provide a link at the new web page.

**Comment by egekorkan** [comment]
Should we still maintain this explainer or https://www.w3.org/WoT/documentation/ is enough?

**Comment by danielpeintner** [comment]
The explainer is far more detailed. Not sure though whether we need this level of details.

If we want to have these information I think we should move it from the TD repository to the marketing repository.

**Comment by egekorkan** [comment]
Call of 18.01:
We should handle this in steps. 
1. Moving the explainer directory to the marketing repository
2. Link the md file on the documentation page
3. Make the md file a jekyll page
4. Rework and update the content so that it becomes a more detailed version of the documentation page which is for now high level
