### ISSUE TITLE
Platforms Communication with Newcomers to WoT

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#146]
In numerous issues of different TFs, we see GitHub issues that are mostly questions from newcomers, i.e. people who are just getting into the WoT. We now have stack overflow tags but there are issues with that as well (see below)

We need a way for newcomers to discuss anything related to the WoT where we or the community can provide correct answers and be welcoming. This was also raised in the plugfest 2021-03 and below are some ideas:

### GitHub discussion pages

I had proposed this in https://github.com/w3c/wot/issues/954 but wasn't well-received by the WG. After thinking for a while, I am not sure if this is enough on its own since we have many repositories where a newcomer can start such a discussion, so we cannot have a nice entry point for them. Maybe our website can fix this by providing an interface to different GitHub repositories to start discussions. 

Also from my experience with students, they are afraid to post a GitHub issue for something they don't understand since it is not a bug. In a way, the word "issue" is pushing people away a bit and is not welcoming.

### Chat platforms

In the plugfest 2021-03, we have seen that Slack works well for us. There is a good amount of activity. Also, this has motivated "total" outsiders to join (https://twitter.com/DylanVanAssche/status/1366743763431919620). However, as expressed in the Slack space, Slack is not very optimal for everyone. However, something similar (a chat platform) could be a very good place for anyone to join and ask us questions. We would be able to monitor the activity (no one getting bad experience) and it would be casual, hopefully encouraging interaction by newcomers.

There are also other options than Slack as mentioned by others:
- Discord
- IRC but with modern clients (IRC Cloud, The Lounge)
- Matrix (and maybe something that works on top of Matrix, e.g. [element.io](https://element.io/), [Discourse](www.discourse.org))

Note: I cannot put the links to the exact discussions in Slack since the link is public but they are in the general channel under a thread by @benfrancis. If it is OK for the group, I can copy-paste the discussion here.

### Problem with Stack Overflow

It is discouraged to ask big questions in stack overflow that may not have a direct answer (https://stackoverflow.com/questions/66412608/guidance-on-implementing-web-of-things-wot-discovery-for-things-and-consumers). Also, even though I was watching the tag, I didn't get an email and someone has downvoted the question. This creates a bad experience for newcomers. 

### Possible Requirements

These are requirements I can think of from the top of my head:
- Easy to join for anyone, i.e. not needing approval from someone
- Allow exchanging "rich text", like code snippets
- Support different channels, i.e. a Telegram group would not fit
- Free to join and to create an account

I would like to discuss this in the F2F of March in a marketing session.

**Comment by benfrancis** [comment]
Historically in my experience most W3C groups have used IRC and mailing lists for these types of discussions. I assume the reason a lot of questions end up on GitHub is that GitHub is more approachable than either of those slightly archaic technologies. For the Web of Things community It's also probably quite confusing to newcomers to know which of the many mailing lists to use between the Community Group, IG and WG. I've never really understood why the #wot IRC channel is only used for keeping meeting minutes, that would be an obvious choice for ongoing synchronous conversations outside of meetings. So the obvious low-effort solution is to more effectively direct people towards a particular mailing list and IRC channel from the website for asking questions.

In my experience at Mozilla, Discourse and Element (Matrix) proved to be good modern/user friendly alternatives to mailing lists and IRC respectively. Discourse and Matrix are both open source projects which can be self-hosted, which is good in that the W3C doesn't have to be dependent on a third party for hosting and archiving content, but they also require a lot of work to install and maintain. Element provides a free instance of Matrix at https://app.element.io that could be used, which supports federation via the open web-based Matrix API (which happens to have a lot in common with the Web of Things).

The new GitHub Discussions feature is interesting because W3C WoT groups already rely heavily on GitHub. GitHub Discussion boards have to be attached to individual GitHub repositories (of which WoT has many) as you say, which may harm discoverability. But that is also true for GitHub issues, which people seem to be using.

I haven't used Discord. I understand that it's popular with many communities, but it is a proprietary platform like Slack.

**Comment by egekorkan** [comment]
@benfrancis In our next F2F on March 25th there will be a marketing slot. Would you be available to join the discussion? (https://www.w3.org/WoT/IG/wiki/F2F_meeting,_March_2021#Marketing_.2840m.29)

@mmccool I think we need a longer timeslot there.

**Comment by benfrancis** [comment]
@egekorkan Unfortunately I may have a conflict that day. If only we had a way to discuss this asynchronously ;)

**Comment by egekorkan** [comment]
In the call of 30.11.2021:
- We should be careful about the maintenance of such a platform. If the current maintainer/moderator does not have time for it, we should find a replacement and define a process for it. This also applies to Twitter.
- @egekorkan will create a Twitter poll to see what our followers there thinks.

**Comment by FadySalama** [comment]
> In the call of 30.11.2021:
> 
> * We should be careful about the maintenance of such a platform. If the current maintainer/moderator does not have time for it, we should find a replacement and define a process for it. This also applies to Twitter.
> * @egekorkan will create a Twitter poll to see what our followers there thinks.

I like the idea of polling the community. Also, another nice, community-driven platform would be Reddit. We can investigate if Reddit is a viable solution as a discussion driven platform that can easily be driven by the community

**Comment by egekorkan** [comment]
The WoT CG has a Discord now, it is solved.
