### ISSUE TITLE
Documenting the Twitter publication rules

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#151]
There are new restrictions communicated in the Main and Marketing Calls (https://www.w3.org/WoT/IG/wiki/Marketing_WebConf#Basic_marketing_policies_for_publication_.28confirmed_on_9_March_2021.29) regarding how Twitter "news" should be handled. 

That text is however underspecified and the minutes are less specified than that.

@ashimura @mlagally @sebastiankb please specify whether this 1-day rule applies to the following types of "news" on Twitter:

- Tweeting a Tweet
- Fleeting a Fleet (an Instagram-like short-lived story)
- Retweeting
- Retweeting with a comment
- Commenting on our Tweet (essential for creating longer tweets in a thread-like fashion)
- Commenting on other people's Tweets
- Liking Tweets and comments (think of the case when we like a WoT related tweet and when we like it, it shows up on our followers' feed)

Also, there are other types of interactions. Does the following need the 1-day rule apply to the following:

- Deleting a Tweet
- Following and unfollowing people. Currently, only W3C or WoT related people are followed.
- Changing our Profile information
- Pinning a Tweet (this shows up as the first tweet in our profile). Currently, the animation video tweet is our pinned tweet. 
- Messaging people

**Comment by mmccool** [comment]
Proposal:

Process (discussed in F2F):
1. Either chair can review a proposed tweet and either authorize it immediately or ask for a 24-hour member review (via email).
2. Either chair can also post a tweet directly.
Because either chair can review, this can be done in any meeting that a chair is present at or via email.
Note: we need to discuss and review the actual text.
This also covers short social media messages other than tweets (facebook posts, fleet,) but only if posting "as" WoT.
Also applies to retweeting, and liking (as WoT, but personal likes are fine).  These are endorsements and need review (unfortunately) or at least another set of eyes to make sure there are no ambiguities or unintended meanings.

In addition: add Ege to the set of people who can post directly.

In addition: just English.

**Comment by mmccool** [comment]
Resolution: passed

**Comment by mmccool** [comment]
To Do: copy the above to the marketing wiki.

**Comment by mmccool** [comment]
Updated, made a few small tweaks to the text, pls take a look.
https://www.w3.org/WoT/IG/wiki/Marketing_WebConf#Policies_and_Publication_Procedures

**Comment by egekorkan** [comment]
We seem to have forgotten to close it.
