### ISSUE TITLE
CG Group links on website

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#270]
see https://www.w3.org/WoT/cg/

We have several links to charter, mailing list but we actually miss a link to the main CG page https://www.w3.org/community/wot/
I suggest to add a link, maybe in the initial paragraph of each CG 

Note: the "chair" part needs to be updated also.

**Comment by egekorkan** [comment]
I would support having the website of CGs properly linked. Regarding the chair, do you mean adding the new chairs after the election process?

**Comment by danielpeintner** [comment]
> Regarding the chair, do you mean adding the new chairs after the election process?

Correct 👍

**Comment by egekorkan** [comment]
Call of 01.03:
- We can have only the link+icon to the main CG page but we should check if there is too much whitespace. The details should/can be changed on their side, it is not "our job".
- We can try to do some tabbing so that different CGs are not listed vertically. This may not be necessary if we reduce the icons to 1.
