### ISSUE TITLE
Landing pages should provide information about TFs

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-marketing#70]
The proposed new landing are a great start to improve transparency and give newcomers a good start.

However the pages for WG /IG have no information about the task forces.
To understand which task forces are active and how to get more information requires deper knowledge about how the groups work, i.e. navigating to the WG/IG main page and digging around.

I suggest to add the task forces to the top level and include links to the task force repos / call information.

We should support the following use case:

As a newcomer I'm interested in the bi-weekly use case call, I want to find out what has been discussed in previous calls, where to find the repo and schedule and dial-in information of the next call.

**Comment by egekorkan** [comment]
Definitely supporting this, even easier now since minutes are public.

**Comment by danielpeintner** [comment]
> A page with a "Task force overview" would be helpful. Maybe not at the very top level, but one link away. A unified Calendar view would also be useful.

see comment in https://github.com/w3c/wot-marketing/issues/71#issuecomment-652384737

Since @mmccool keeps up-to-date outlook invitations for all meetings I suggest we create an online iCal file for that. This brings the advantage that we can use the *same* file for keeping calendar entries in sync and also render them on our website (there are tools like [calendarview](https://github.com/luser/calendarview) that nicely render it)

The calendar entry may contain additional useful information...

**Comment by egekorkan** [comment]
In the call of 9.2.2021, we have decided to close this issue since the TF overviews already exist.
